export const authConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCESS:'LOGIN_SUCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCESS:'LOGOUT_SUCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'
}

export const userConstants={
    USER_REGISER_REQUEST:'USER_REGISER_REQUEST',
    USER_REGISER_FAILURE:'USER_REGISER_FAILURE',
    USER_REGISER_SUCESS:'USER_REGISER_SUCESS',
}

export const categotyConstants={
    CATEGORY_REQUEST:'CATEGORY_REQUEST',
    CATEGORY_FAILURE:'CATEGORY_FAILURE',
    CATEGORY_SUCESS:'CATEGORY_SUCESS',
    ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_FAILURE:'ADD_CATEGORY_FAILURE',
    ADD_CATEGORY_SUCESS:'ADD_CATEGORY_SUCESS',
}

export const productsConstants={
    ADD_PRODUCTS_REQUEST:'PRODUCTS_REQUEST',
    ADD_PRODUCTS_FAILURE:'PRODUCTS_FAILURE',
    ADD_PRODUCTS_SUCESS:'PRODUCTS_SUCESS',
}

export const getproductsConstants={
    GET_PRODUCTS_REQUEST:'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_FAILURE:'GET_PRODUCTS_FAILURE',
    GET_PRODUCTS_SUCESS:'GET_PRODUCTS_SUCESS',
}

export const initDataConstants={
    GET_ALL_INITDATA_REQUEST:'GET_ALL_INITDATA_REQUEST',
    GET_ALL_INITDATA_FAILURE:'GET_ALL_INITDATA_FAILURE',
    GET_ALL_INITDATA_SUCESS:'GET_ALL_INITDATA_SUCESS',
}
export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };
