export const authConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCESS:'LOGIN_SUCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCESS:'LOGOUT_SUCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'
}

export const userConstants={
    USER_REGISER_REQUEST:'USER_REGISER_REQUEST',
    USER_REGISER_FAILURE:'USER_REGISER_FAILURE',
    USER_REGISER_SUCESS:'USER_REGISER_SUCESS',
}

export const categotyConstants={
    CATEGORY_REQUEST:'CATEGORY_REQUEST',
    CATEGORY_FAILURE:'CATEGORY_FAILURE',
    CATEGORY_SUCESS:'CATEGORY_SUCESS',
}


export const getproductsConstants={
    GET_PRODUCTS_REQUEST:'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_FAILURE:'GET_PRODUCTS_FAILURE',
    GET_PRODUCTS_SUCESS:'GET_PRODUCTS_SUCESS',
}

export const getproductsListBySlugConstants={
    GET_PRODUCTSLIST_BYSLUG:'GET_PRODUCTSLIST_BYSLUG',
    GET_PRODUCTSLIST_BYSLUG_DEFAULT:'GET_PRODUCTSLIST_BYSLUG_DEFAULT',
}

export const getProductsPageConstants={
    GET_PRODUCTS_PAGE_REQUEST:'GET_PRODUCTS_PAGE_REQUEST',
    GET_PRODUCTS_PAGE_FAILURE:'GET_PRODUCTS_PAGE_FAILURE',
    GET_PRODUCTS_PAGE_SUCESS:'GET_PRODUCTS_PAGE_SUCESS',
}



export const getProductByIdConstants={
    GET_PRODUCT_BY_ID_REQUEST:'GET_PRODUCT_BY_ID_REQUEST',
    GET_PRODUCT_BY_ID_SUCESS:'GET_PRODUCT_BY_ID_SUCESS',
    GET_PRODUCT_BY_ID_FAILURE:'GET_PRODUCT_BY_ID_FAILURE',
}

export const cartConstants={
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCESS:'ADD_TO_CART_SUCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    RESET_CART:'RESET_CART',

    
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE"
}


export const userDetailsConstants = {
    GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
    ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
    ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
    ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
    GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
    GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
  };